version: '3.9'

# todo => maybe work with K8s in this project

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
      - mongodb
      - mssql-server

  mongodb:
    image: mongo:latest
    user: root
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "mongodb_data:/data/db"

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - mssqlserver_data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Testing123!
    ports:
      - "1433:1433"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data:
    driver: local
  mssqlserver_data:
    driver: local

networks:
  default:
    external:
      name: microservices-network
